on: 
  push

jobs:
  post-command:
    runs-on: ubuntu-latest
    name: execution create.ts
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      Application_ID: ${{ secrets.Application_ID }}
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19.1
        with:
          fetch-depth: 2

      - name: Checkout
        uses: actions/checkout@v3

      - name: execute
        if: env.BOT_TOKEN != null && env.Application_ID != null && contains(steps.changed-files.outputs.all_modified_files, 'src/create.ts')
        uses: ./